apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: blipp
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: blipp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth
          image: blipp-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak.blipp.svc.cluster.local:8080/keycloak"
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: blipp-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blipp-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
