"""
Focused unit tests for transactional outbox event envelope hardening:
- Test A: Canonical identity (returned UUID == outbox_events.id == payload.event_id)
- Test B: Reserved fields cannot be overridden by caller
- Test C: occurred_at exists, is non-null, valid ISO-8601, and matches insertion time
- Test D: Publisher preserves envelope when publishing to NATS
"""

import asyncio
import json
import unittest
import uuid
from datetime import datetime, timezone, timedelta
from unittest.mock import AsyncMock, MagicMock, patch

import blipp_common.outbox as outbox
from blipp_common.outbox import (
    record_outbox_event,
    run_outbox_publisher,
    stop_outbox_publisher,
    RESERVED_ENVELOPE_FIELDS,
)


class TestOutboxEnvelope(unittest.IsolatedAsyncioTestCase):
    """Test suite for transactional outbox event envelope contract."""

    async def test_canonical_identity(self):
        """
        Test A — canonical identity:
        After calling record_outbox_event():
        - returned UUID == outbox_events.id
        - payload.event_id == outbox_events.id
        - all three values are identical
        """
        mock_conn = AsyncMock()

        subject = "engagement.blipp.published"
        caller_payload = {
            "blipp_id": str(uuid.uuid4()),
            "creator_id": str(uuid.uuid4()),
            "title": "My Broadcast",
        }

        returned_eid = await record_outbox_event(mock_conn, subject, caller_payload)

        # Verify conn.execute was called
        mock_conn.execute.assert_called_once()
        sql, inserted_id, inserted_subject, inserted_payload_json, inserted_created_at = (
            mock_conn.execute.call_args[0]
        )

        inserted_payload = json.loads(inserted_payload_json)

        # Assert returned UUID is a valid UUID
        self.assertIsInstance(returned_eid, uuid.UUID)

        # Assert returned UUID == outbox_events.id ($1)
        self.assertEqual(returned_eid, inserted_id)

        # Assert payload.event_id == outbox_events.id
        self.assertEqual(uuid.UUID(inserted_payload["event_id"]), inserted_id)

        # Assert all three values are identical
        self.assertEqual(str(returned_eid), str(inserted_id))
        self.assertEqual(str(returned_eid), inserted_payload["event_id"])

    async def test_reserved_fields_cannot_be_overridden(self):
        """
        Test B — reserved fields cannot be overridden:
        Pass a payload containing fake event_id, event_type, occurred_at and verify
        the persisted envelope contains the canonical values generated by
        record_outbox_event() rather than caller-supplied values.
        """
        mock_conn = AsyncMock()

        subject = "upload.received"
        fake_payload = {
            "event_id": "00000000-0000-0000-0000-000000000000",
            "event_type": "fake.event.type",
            "occurred_at": "1999-01-01T00:00:00+00:00",
            # Legitimate domain fields must be preserved
            "upload_id": "test-upload-123",
            "creator_id": "test-creator-456",
        }

        returned_eid = await record_outbox_event(mock_conn, subject, fake_payload)

        sql, inserted_id, inserted_subject, inserted_payload_json, inserted_created_at = (
            mock_conn.execute.call_args[0]
        )
        inserted_payload = json.loads(inserted_payload_json)

        # 1. event_id must NOT be the fake caller event_id
        self.assertNotEqual(inserted_payload["event_id"], "00000000-0000-0000-0000-000000000000")
        self.assertEqual(inserted_payload["event_id"], str(returned_eid))
        self.assertEqual(inserted_id, returned_eid)

        # 2. event_type must be the canonical subject, NOT caller fake
        self.assertNotEqual(inserted_payload["event_type"], "fake.event.type")
        self.assertEqual(inserted_payload["event_type"], subject)

        # 3. occurred_at must NOT be the fake caller timestamp
        self.assertNotEqual(inserted_payload["occurred_at"], "1999-01-01T00:00:00+00:00")

        # 4. Domain fields must be fully preserved
        self.assertEqual(inserted_payload["upload_id"], "test-upload-123")
        self.assertEqual(inserted_payload["creator_id"], "test-creator-456")

    async def test_occurred_at_exists_and_accurate(self):
        """
        Test C — occurred_at exists:
        Verify:
        - payload["occurred_at"] is not null
        - it is parseable as an ISO-8601 timestamp
        - it represents approximately the outbox insertion time
        - it matches the persisted outbox created_at timestamp
        """
        mock_conn = AsyncMock()

        before_call = datetime.now(timezone.utc)
        returned_eid = await record_outbox_event(
            mock_conn, "engagement.like", {"blipp_id": str(uuid.uuid4()), "user_id": str(uuid.uuid4())}
        )
        after_call = datetime.now(timezone.utc)

        sql, inserted_id, inserted_subject, inserted_payload_json, inserted_created_at = (
            mock_conn.execute.call_args[0]
        )
        inserted_payload = json.loads(inserted_payload_json)

        # 1. occurred_at is present and not null
        self.assertIn("occurred_at", inserted_payload)
        self.assertIsNotNone(inserted_payload["occurred_at"])

        # 2. parseable as ISO-8601
        parsed_dt = datetime.fromisoformat(inserted_payload["occurred_at"])
        self.assertIsNotNone(parsed_dt.tzinfo)

        # 3. represents approximately the outbox insertion time
        self.assertTrue(before_call - timedelta(seconds=1) <= parsed_dt <= after_call + timedelta(seconds=1))

        # 4. matches the created_at parameter passed to SQL insert ($4)
        self.assertIsInstance(inserted_created_at, datetime)
        self.assertEqual(inserted_created_at.isoformat(), inserted_payload["occurred_at"])

    async def test_publisher_preserves_envelope(self):
        """
        Test D — publisher preserves envelope:
        Verify that run_outbox_publisher() sends the exact persisted payload to NATS
        without regenerating event_id, changing occurred_at, or dropping domain fields.
        """
        canonical_eid = uuid.uuid4()
        canonical_occurred_at = "2026-09-17T18:00:00.123456+00:00"
        subject = "engagement.save"

        persisted_payload = {
            "event_id": str(canonical_eid),
            "event_type": subject,
            "occurred_at": canonical_occurred_at,
            "blipp_id": str(uuid.uuid4()),
            "user_id": str(uuid.uuid4()),
        }

        fake_row = {
            "id": canonical_eid,
            "subject": subject,
            "payload": json.dumps(persisted_payload),
            "retry_count": 0,
        }

        # Setup mock pool with async context managers for asyncpg
        mock_conn = MagicMock()
        mock_conn.execute = AsyncMock()
        mock_conn.fetch = AsyncMock(return_value=[fake_row])

        mock_tx = AsyncMock()
        mock_tx.__aenter__.return_value = mock_tx
        mock_tx.__aexit__.return_value = None
        mock_conn.transaction = MagicMock(return_value=mock_tx)

        mock_pool = MagicMock()
        mock_acquire_cm = AsyncMock()
        mock_acquire_cm.__aenter__.return_value = mock_conn
        mock_acquire_cm.__aexit__.return_value = None
        mock_pool.acquire = MagicMock(return_value=mock_acquire_cm)

        published_events = []

        async def mock_publish(subject, payload):
            published_events.append((subject, payload))
            # Stop publisher after publishing the first batch
            outbox.stop_outbox_publisher()

        with patch("blipp_common.outbox.event_bus") as mock_event_bus:
            mock_event_bus.is_connected = True
            mock_event_bus.js = MagicMock()
            mock_event_bus.publish = AsyncMock(side_effect=mock_publish)

            outbox._outbox_running = True
            await asyncio.wait_for(
                outbox.run_outbox_publisher(mock_pool, service_name="test-publisher", poll_interval_seconds=0.01),
                timeout=3.0,
            )

        # Verify NATS publish was called with exact persisted payload
        self.assertEqual(len(published_events), 1)
        published_subject, published_payload = published_events[0]

        self.assertEqual(published_subject, subject)
        self.assertEqual(published_payload["event_id"], str(canonical_eid))
        self.assertEqual(published_payload["occurred_at"], canonical_occurred_at)
        self.assertEqual(published_payload["event_type"], subject)
        self.assertEqual(published_payload["blipp_id"], persisted_payload["blipp_id"])
        self.assertEqual(published_payload["user_id"], persisted_payload["user_id"])


if __name__ == "__main__":
    unittest.main()
