apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  namespace: blipp
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: event-bus
    app.kubernetes.io/part-of: blipp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
