apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: blipp
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: event-bus
    app.kubernetes.io/part-of: blipp
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
  selector:
    app.kubernetes.io/name: nats
