apiVersion: v1
kind: Service
metadata:
  name: social-graph-service
  namespace: blipp
  labels:
    app.kubernetes.io/name: social-graph-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: blipp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  selector:
    app.kubernetes.io/name: social-graph
