#!/usr/bin/env bash
set -euo pipefail

# Determine repository and app directories
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="${REPO_ROOT}/apps/blipp"
NAMESPACE="${NAMESPACE:-blipp}"

echo "============================================================"
echo "🚀 Blipp Mobile Development Environment (Expo Go)          "
echo "============================================================"

# 1. Detect LAN IP (Cross-platform: macOS & Linux)
if [ -n "${LAN_IP:-}" ]; then
  DETECTED_IP="$LAN_IP"
  echo "ℹ️ Using LAN_IP from environment: ${DETECTED_IP}"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  DETECTED_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)
  if [ -z "$DETECTED_IP" ]; then
    DETECTED_IP=$(scutil --nwi 2>/dev/null | grep address | awk '{print $3}' | head -n 1 || true)
  fi
else
  # Linux: default route IP or first non-loopback IP
  DETECTED_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || true)
  if [ -z "$DETECTED_IP" ]; then
    DETECTED_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
  fi
fi

if [ -z "$DETECTED_IP" ] || [[ "$DETECTED_IP" == "127."* ]]; then
  echo "❌ Error: Could not automatically detect a valid non-loopback LAN IP."
  echo "   Please specify your LAN IP manually: LAN_IP=192.168.1.X $0"
  exit 1
fi

echo "✅ Detected LAN IP: ${DETECTED_IP}"

# 2. Configure apps/blipp/.env
ENV_FILE="${APP_DIR}/.env"
echo "⚙️ Configuring ${ENV_FILE}..."

cat <<EOF > "${ENV_FILE}"
# Auto-generated by scripts/dev-mobile.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EXPO_PUBLIC_API_URL=http://${DETECTED_IP}:8000/v1
EXPO_PUBLIC_KEYCLOAK_URL=http://${DETECTED_IP}:8080/keycloak
EOF

echo "   EXPO_PUBLIC_API_URL=http://${DETECTED_IP}:8000/v1"
echo "   EXPO_PUBLIC_KEYCLOAK_URL=http://${DETECTED_IP}:8080/keycloak"

# 3. Verify Kubernetes namespace
if ! kubectl get namespace "${NAMESPACE}" >/dev/null 2>&1; then
  echo "❌ Error: Cannot communicate with Kubernetes namespace '${NAMESPACE}'."
  echo "   Ensure your cluster is running (e.g. 'make cluster-up' or 'k3d cluster list')."
  exit 1
fi

# 4. Background Port Forwarding with Cleanup Trap
echo "🔗 Starting Kubernetes port-forwarding on 0.0.0.0 for LAN access..."

PIDS=()

cleanup() {
  echo ""
  echo "🛑 Shutting down port-forwarding processes..."
  for pid in "${PIDS[@]:-}"; do
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  echo "✅ Mobile development environment stopped."
}

trap cleanup EXIT INT TERM

# Port-forward auth-service, content-ingest-service, feed-service, keycloak, and minio
kubectl port-forward --address 0.0.0.0 svc/auth-service 8000:8000 -n "${NAMESPACE}" >/dev/null 2>&1 &
PIDS+=($!)

kubectl port-forward --address 0.0.0.0 svc/content-ingest-service 8001:8001 -n "${NAMESPACE}" >/dev/null 2>&1 &
PIDS+=($!)

kubectl port-forward --address 0.0.0.0 svc/feed-service 8002:8002 -n "${NAMESPACE}" >/dev/null 2>&1 &
PIDS+=($!)

kubectl port-forward --address 0.0.0.0 svc/keycloak 8080:8080 -n "${NAMESPACE}" >/dev/null 2>&1 &
PIDS+=($!)

kubectl port-forward --address 0.0.0.0 svc/minio 9000:9000 -n "${NAMESPACE}" >/dev/null 2>&1 &
PIDS+=($!)

# Brief pause to verify processes are alive
sleep 2
for pid in "${PIDS[@]}"; do
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "⚠️ Warning: A port-forward process (PID $pid) failed to start. Port may already be in use."
  fi
done

echo "✅ Port-forwarding active:"
echo "   - Auth Service:   http://${DETECTED_IP}:8000"
echo "   - Content Ingest: http://${DETECTED_IP}:8001"
echo "   - Feed Service:   http://${DETECTED_IP}:8002"
echo "   - Keycloak:       http://${DETECTED_IP}:8080/keycloak"
echo "   - MinIO S3:       http://${DETECTED_IP}:9000"

echo ""
echo "📱 Launching Expo development server..."
echo "   Scan the QR code in the Expo Go app on your physical mobile device."
echo "   (Make sure your phone is connected to the same Wi-Fi network as this machine)"
echo "   Press Ctrl+C to stop the dev server and port-forwarding."
echo ""

cd "${APP_DIR}"
if [ "$#" -gt 0 ]; then
  npx expo start --host lan "$@"
else
  npm run start:lan
fi
