replicaCount: 1

image:
  repository: blipp-auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "auth-service"

podAnnotations:
  linkerd.io/inject: enabled

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

secretName: blipp-secrets

env:
  keycloakUrlKey: KEYCLOAK_URL
  keycloakInternalUrlKey: KEYCLOAK_INTERNAL_URL
  keycloakRealmKey: KEYCLOAK_REALM
  keycloakClientIdKey: KEYCLOAK_CLIENT_ID
  keycloakClientSecretKey: KEYCLOAK_CLIENT_SECRET
  keycloakAdminKey: KEYCLOAK_ADMIN
  keycloakAdminPasswordKey: KEYCLOAK_ADMIN_PASSWORD

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 3

nodeSelector: {}
tolerations: []
affinity: {}
